modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/squeek502/AppleSkin"

[[mods]]
modId="appleskin"
version="${version}"
displayName="AppleSkin"
#updateJSONURL=""
displayURL="https://github.com/squeek502/AppleSkin"
#logoFile="appleskin.png"
authors="squeek"
description="Adds various food-related HUD improvements"

# Required for PlayerEvent/TickEvent change in 28.0.45
[[dependencies.appleskin]]
    modId="forge"
    mandatory=true
    versionRange="[28.0.45,)"
    ordering="NONE"
    side="BOTH"