modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/squeek502/AppleSkin"
license="The Unlicense"

[[mods]]
modId="appleskin"
version="${file.jarVersion}"
displayName="AppleSkin"
#updateJSONURL=""
displayURL="https://github.com/squeek502/AppleSkin"
logoFile="appleskin.png"
authors="squeek"
description="Adds various food-related HUD improvements"

[[dependencies.appleskin]]
    modId="neoforge"
    type="required"
    versionRange="[20.4,)"
    ordering="NONE"
    side="CLIENT"